name: YeeFlow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4
      - name: Verificar chave SSH
        run: ssh ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} "cat ~/.ssh/authorized_keys"
      - name: Deploy para o servidor
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.REMOTE_SSH_KEY}}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/."
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          REMOTE_PORT: ${{secrets.REMOTE_PORT}}
          TARGET: ${{secrets.REMOTE_TARGET}}
      - name: Setup App
        run: sudo systemctl restart yee_api
